package com.helm.engine

import androidx.biometric.BiometricManager
import androidx.biometric.BiometricPrompt
import androidx.fragment.app.FragmentActivity
import java.util.concurrent.Executor
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlinx.coroutines.suspendCancellableCoroutine

/**
 * Biometric gate for sensitive actions (DESIGN.md §8.4).
 *
 * The SSH device key currently lives in app-private storage generated by the
 * Rust FileKeyStore ([HelmRepository.pair] → `pair_enroll`), which keeps it
 * non-exportable off-device (allowBackup=false). Full hardware isolation —
 * an ed25519/P-256 key in Android Keystore/StrongBox with
 * `setUserAuthenticationRequired(true)`, signing SSH challenges via a russh
 * custom-signer callback across the FFI — is the production hardening step
 * tracked in android/README.md. This class provides the biometric gate that
 * hardening plugs into, and gates key-using actions today.
 */
object DeviceKeystore {

    fun canAuthenticate(activity: FragmentActivity): Boolean {
        val bm = BiometricManager.from(activity)
        return bm.canAuthenticate(
            BiometricManager.Authenticators.BIOMETRIC_STRONG,
        ) == BiometricManager.BIOMETRIC_SUCCESS
    }

    /** Prompt for biometric confirmation; resumes true on success. */
    suspend fun authenticate(
        activity: FragmentActivity,
        title: String,
        subtitle: String,
    ): Boolean = suspendCancellableCoroutine { cont ->
        if (!canAuthenticate(activity)) {
            // No biometrics enrolled: allow, but this is where a policy could
            // require device credentials instead.
            cont.resume(true)
            return@suspendCancellableCoroutine
        }
        val executor: Executor = activity.mainExecutor
        val prompt = BiometricPrompt(
            activity,
            executor,
            object : BiometricPrompt.AuthenticationCallback() {
                override fun onAuthenticationSucceeded(result: BiometricPrompt.AuthenticationResult) {
                    if (cont.isActive) cont.resume(true)
                }

                override fun onAuthenticationError(code: Int, msg: CharSequence) {
                    if (cont.isActive) cont.resumeWithException(SecurityException("biometric: $msg"))
                }

                override fun onAuthenticationFailed() { /* ret/ry loop handled by prompt */ }
            },
        )
        val info = BiometricPrompt.PromptInfo.Builder()
            .setTitle(title)
            .setSubtitle(subtitle)
            .setNegativeButtonText("Cancel")
            .setAllowedAuthenticators(BiometricManager.Authenticators.BIOMETRIC_STRONG)
            .build()
        prompt.authenticate(info)
        cont.invokeOnCancellation { prompt.cancelAuthentication() }
    }
}
